### ISSUE TITLE
Copy/Cut and Paste Behaviour Not Working as Expected

### ISSUE THREAD

**Issue by CCattano** [2mas/SelectNextOccurrence#36] opened 2019-04-15 17:01 UTC
### Installed product versions
- Visual Studio: Visual Studio Professional 2019 16.0.1
- This extension: 1.3.83

### Description
I am experiencing the exact behaviour that was expressed in closed issue #4 

From looking at the change logs it looks like this was resolved in v1.2 so I'm assuming this is due to something I've implemented incorrectly.

### Steps to recreate/Current behavior/Expected behavior

If you reference Issue 4 that is linked above, everything I would type for this section would be a verbatim retelling of what user, busterwood, has already taken the time to write and explain.

Maybe this fixed functionality may have been broken due to later changes? If there is more information I can provide that I have left out, I apologize, please just let me know.

Thanks so much btw for the time and effort put into this extension. Ever since MixEdit was removed from the VS Marketplace I was never able to find a comparable extension to replace it until now. I really can't thank you enough.

**Comment by 2mas** [comment] 2019-04-16 06:11
Hi! Thanks for taking your time to report this and I'm happy you like it!

Multi copy/paste works for me with VS 2019. Could you please check if you have the extension **Copy As Html** active? If not, could you please provide me with a list of installed extensions? I suspect this might be an interference

To get extension list:
```Help -> About Microsoft Visual Studio -> Copy Info```

**Comment by CCattano** [comment] 2019-04-16 12:57
> Hi! Thanks for taking your time to report this and I'm happy you like it!
> 
> Multi copy/paste works for me with VS 2019. Could you please check if you have the extension **Copy As Html** active? If not, could you please provide me with a list of installed extensions? I suspect this might be an interference
> 
> To get extension list:
> `Help -> About Microsoft Visual Studio -> Copy Info`

I wasn't seeing Copy As Html in my list of extensions. Here's the contents from Help -> About -> Copy Info

```
Microsoft Visual Studio Professional 2019
Version 16.0.1
VisualStudio.16.Release/16.0.1+28803.156
Microsoft .NET Framework
Version 4.7.03062

Installed Version: Professional

Visual C++ 2019   00435-60000-00000-AA156
Microsoft Visual C++ 2019

Application Insights Tools for Visual Studio Package   9.0.20307.1
Application Insights Tools for Visual Studio

ASP.NET and Web Tools 2019   16.0.12311.10635
ASP.NET and Web Tools 2019

ASP.NET Core Blazor Language Services   16.0.19154.02

ASP.NET Web Frameworks and Tools 2019   16.0.12311.10635
For additional information, visit https://www.asp.net/

Azure App Service Tools v3.0.0   16.0.12311.10635
Azure App Service Tools v3.0.0

Azure Functions and Web Jobs Tools   16.0.12311.10635
Azure Functions and Web Jobs Tools

C# Tools   3.0.0-beta4-19170-01+1deafee3682da88bf07d1c18521a99f47446cee8
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Microsoft Azure Tools   2.9
Microsoft Azure Tools for Microsoft Visual Studio 0x10 - v2.9.0.0

Microsoft Continuous Delivery Tools for Visual Studio   0.4
Simplifying the configuration of Azure DevOps pipelines from within the Visual Studio IDE.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft Library Manager   1.0
Install client-side libraries easily to any web project

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual C++ Wizards   1.0
Microsoft Visual C++ Wizards

Microsoft Visual Studio Tools for Containers   1.1
Develop, run, validate your ASP.NET Core applications in the target environment. F5 your application directly into a container with debugging, or CTRL + F5 to edit & refresh your app without having to rebuild the container.

Microsoft Visual Studio VC Package   1.0
Microsoft Visual Studio VC Package

Node.js Tools   1.5.10301.2 Commit Hash:9c34eb81d73db6babeb71674feb1cb437dba9f2f
Adds support for developing and debugging Node.js apps in Visual Studio

NuGet Package Manager   5.0.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit http://docs.nuget.org/.

Open Command Line   2.1.218
Opens a command line at the root of the project. Support for all consoles such as CMD, PowerShell, Bash etc. Provides syntax highlighting, Intellisense and execution of .cmd and .bat files.

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

ResourcePackage Extension   1.0
ResourcePackage Visual Studio Extension Detailed Info

ResourcePackage Extension   1.0
ResourcePackage Visual Studio Extension Detailed Info

Select Next Occurrence   1.3.83
Selects the next occurrence of the current selection and adds multiple cursors for editing.

SQL Server Data Tools   16.0.61903.25110
Microsoft SQL Server Data Tools

TypeScript Tools   16.0.10306.2001
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   3.0.0-beta4-19170-01+1deafee3682da88bf07d1c18521a99f47446cee8
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual F# Tools 10.4 for F# 4.6   16.0.0.0.  Commit Hash: 809f41207b74a1356208f11b8fa3a15233734050.
Microsoft Visual F# Tools 10.4 for F# 4.6

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

Visual Studio Tools for Containers   1.0
Visual Studio Tools for Containers
```

**Comment by 2mas** [comment] 2019-04-18 06:24
Thanks, I cant see any obvious interfering extensions there. I you dont mind, would you please check for me which command is actually run when you press copy and paste?

To do this check, go to the keyboard-shortcut settings and take any random command in the list, then in the Press shortcut keys, enter the shortcut for copy and for paste and see if they are using ```Edit.Copy``` and ```Edit.Paste``` commands (and also see if it might be overriden in the Text Editor-area):

![image](https://user-images.githubusercontent.com/372362/56340505-62bae800-61b2-11e9-916f-ec0bc027e44b.png)

**Comment by CCattano** [comment] 2019-04-22 14:21
Hey 2mas, I'm so sorry for the delay in getting back to you, I got wrapped up in work and life and totally spaced that we were having this back and forth, again, super sorry.

I checked out my keyboard bindings and for Copy I'm using `Edit.Copy(Ctrl+C (Global))` and for Paste I'm using `Edit.Paste (Ctrl+V (Global))`

Both of these commands are being used in the `Global` and `Text Editor` areas

![image](https://user-images.githubusercontent.com/47487276/56504941-d4ab6e00-64df-11e9-9147-de9d39fc659a.png)

![image](https://user-images.githubusercontent.com/47487276/56504954-decd6c80-64df-11e9-97db-75caf58f035c.png)

![image](https://user-images.githubusercontent.com/47487276/56504969-e7be3e00-64df-11e9-83d6-ee11e270fe17.png)

![image](https://user-images.githubusercontent.com/47487276/56505001-ff95c200-64df-11e9-8254-dcd019ca21b2.png)

Should I have it set up to be using something else?

**Comment by 2mas** [comment] 2019-04-23 06:25
Thanks for checking! Sounds like we are in the same situation, alot with work and life here too :)

Can't really think of a reason why this fails and I can't reproduce. Does this behave in the same way every time? What type of file is it? Any other programs running that might block the clipboard or something?

When busterwood reported this, this feature did not exist to handle multiple copy/paste.

**Comment by CCattano** [comment] 2019-05-03 20:32
So I've actually accidentally stumbled across some new information in regards to this issue which also reminded me I had opened this issue. So sorry to have just let it hang open this long without getting back to you.

I'm not sure if this new observed behaviour warrants opening a new issue all together and closing this one or not, but I'll lay it out here and can open a different one if needed. Just let me know!

# Steps To Recreate
So here's what I've come to find. Given the following text in a VS editor

```
const var1: string = "test1";
const var2: string = "test2";
const var3: string = "test3";

const var4: string = "test4";
const var5: string = "test5";
const var6: string = "test6";
```

1. `Double-click` to select the word `const` that is associated with `var1`
2. Use `Ctrl+D` to select the `const` keyword associated with `var2` and `var3`
3. Press the `End` key to move the cluster of cursors to the end of their respective lines
4. Press `Left Arrow` twice to align the cursors on the left side of the right quotation mark
5. Hold `Ctrl+Shift` and press `Left Arrow` to select `test1`, `test2`, `test3`
6. Press `Ctrl+C` to copy
7. (*Important*) Break the cursor clusterby `double-clicking` the `const` keyword associated with `var4` to select it
8. Repeat steps `1 through 5` to select `test4`, `test5`, `test6`
9. Press `Ctrl+V` to paste

# Current Behaviour
The steps above result in the text below for me

```
const var1: string = "test1";
const var2: string = "test2";
const var3: string = "test3";

const var4: string = "test3";
const var5: string = "test3";
const var6: string = "test3";
```

Here is a gif I threw together demonstrating the occurrence 
![SelectNextUnexpected](https://user-images.githubusercontent.com/47487276/57164019-740e1200-6db8-11e9-8b27-3aa135416bd7.gif)


# Expected Behaviour
```
const var1: string = "test1";
const var2: string = "test2";
const var3: string = "test3";

const var4: string = "test1";
const var5: string = "test2";
const var6: string = "test3";
```

# Important Things To Note

What I've accidentally stumbled upon and discovered is that if you omit `Step 7` of the reproduction step process and instead navigate to and align the cursor cluster with `test4`, `test5`, `test6` manually via the arrow keys, never breaking the cluster, and then use `Ctrl+V` to paste then you will see the expected behaviour.

Here is a gif I made to show that behaviour in action
![SelectNextExpected](https://user-images.githubusercontent.com/47487276/57164048-84be8800-6db8-11e9-8313-5b9dd638ac02.gif)


The problem with this for me at least, is that I may copy two or three items right on top of one another, but then they need to be pasted in completely different locations throughout whatever document I am working in. So I can't manually navigate the cursor cluster to each individual location without breaking it and starting a new cursor cluster with `Ctrl+D` or `Ctrl+Click` to place cursors.

It seems that, for me at least, what's breaking the expected behaviour is the act of copying content via one cursor cluster, then breaking that cluster, going back to a single cursor, and creating a new cluster before pasting the copied content.

I hope that makes sense! If I need to explain anything better please let me know!

**Comment by 2mas** [comment] 2019-05-04 05:07
Ah, thats the piece of the puzzle I was missing, the one where you made new selections. The copied text is tied to the selection so that’s why it fails. Could this have been a step in the original problem described aswell?

I’ll see if I can come up with a fix for this

**Comment by 2mas** [comment] 2019-05-08 10:20
Master now contains a new behaviour for copy/paste that should fix this. Testning it now and a new release is coming up

**Comment by 2mas** [comment] 2019-05-14 11:33
New version released, please update and see if this fixes the issue

**Comment by Wikster2012** [comment] 2019-05-15 18:24
The update has fixed the issue and the copy/paste behaviour is working as expected. Thanks so much for taking the time to put this change in and thanks so much for this great extension!

**Comment by 2mas** [comment] 2019-05-16 16:08
Awesome to hear that @Wikster2012! I’m closing this, please reopen if there still are issues @CCattano

**Closed by 2mas** 2019-05-16 16:08 UTC
