### ISSUE TITLE
Copy/paste multiple selections to one cardet

### ISSUE THREAD

**Issue by PSonneveld** [2mas/SelectNextOccurrence#9] opened 2018-05-03 07:50 UTC
### Installed product versions
- Visual Studio: 2017 CE
- This extension: 1.2.17

### Description
Pasting multiple selections to one cardet only paste the last selection.
(I do not have the "copy as html" plugin installed)

### Steps to recreate
Given this text
```
DataGrid.CreateDataSet("Data1");
DataGrid.CreateDataSet("Data2");
DataGrid.CreateDataSet("Data3");
```
1. select the word DataGrid
2. press ctrl-d multiple times to select all occurances (or other shortcut)
3. press ctrl + right three times to more the cursor to the first letter of dataset name
4. press shift-ctrl-right to select the names
5. press ctrl-c to copy to clipboard
6. click somewhere in the file so only one cardet is left
7. paste

### Current behavior
Currently it only paste the last selection and loses the rest
```
DataGrid.CreateDataSet("Data1");
DataGrid.CreateDataSet("Data2");
DataGrid.CreateDataSet("Data3");

Data3
```

### Expected behavior
I expected to have all values pasted (like in other editors, e.g. atom, sublime)
```
DataGrid.CreateDataSet("Data1");
DataGrid.CreateDataSet("Data2");
DataGrid.CreateDataSet("Data3");

Data1
Data2
Data3
```

**Comment by 2mas** [comment] 2018-05-07 09:41
Hi and thanks for reporting. I have added this on the dev-branch to be tested. I think it works good but if you have time to check it, please try this [CI build](http://vsixgallery.com/extensions/NextOccurrence.b213c4e9-b96f-4f9d-b1d6-fa8bc7e9da21/Select%20Next%20Occurrence%20v1.2.22.vsix)

**Comment by 2mas** [comment] 2018-05-08 11:11
@PSonneveld I updated the extension on the VS Gallery with this ability. Closing this, if it doesnt work as expected please write me a comment

**Comment by PSonneveld** [comment] 2018-05-08 21:02
Thanks for looking into it and for this awesome extension. I wasn't able to test it properly since I was working on another machine.

**Comment by Goesenroos** [comment] 2018-05-14 05:51
So I installed visual studio 2017 on my work machine and installed the latest version of the plugin (1.2.23). When I follow the case above it gives me an error.
![bug](https://user-images.githubusercontent.com/19855399/39980250-30327d02-574b-11e8-9c78-3e8f80ad9ce2.jpg)
however the file it mentions is not present.

I encountered more bugs with clipboard, but I can't reproduce it yet

**Comment by 2mas** [comment] 2018-05-29 19:58
Closing this for now, can’t reproduce any errors. @Goesenroos re-open this if you can reproduce or get me a log, thanks

**Closed by 2mas** 2018-05-29 19:58 UTC
