### ISSUE TITLE
Dot character only added to the last selection

### ISSUE THREAD

**Issue by argontus** [2mas/SelectNextOccurrence#13] opened 2018-07-07 19:19 UTC
### Installed product versions
- Visual Studio: 2017
- This extension: 1.3.32

### Description
Adding a dot character after writing (a-z) characters only adds the dot in the last selection caret.

### Steps to recreate
1. Select some word that occurs multiple times
2. Write another word to replace the selected occurrences
3. Write a dot character "."

### Current behavior
Only the last selection caret gets the dot character added

### Expected behavior
All of the selections should get the dot character added

**Comment by 2mas** [comment] 2018-07-08 10:29
Hi and thanks for reporting, I cannot reproduce this however. I have tried VS 2015/2017 plus the preview-version. This sounds like another extension interfering to me. Have this behavior suddenly started after other extensions being activated? If you find any extension that you suspect could cause this, please try and disable just to check if it is the cause

**Comment by drewnoakes** [comment] 2018-07-08 10:37
@argontus do you have ReSharper installed?

@2mas do you know if this extension conflicts with ReSharper?

**Comment by argontus** [comment] 2018-07-09 06:16
@2mas @drewnoakes Thanks for pointing out that possibility. I don't have ReSharper, but turned out that the culprit is Visual Assist X. More specifically, the feature that turns "." into "->" if the dot was entered after a pointer symbol.

Not sure if there's anything that can be done to circumvent that, but at least if someone else has problems with this, the dot-to-arrow feature can be turned off in VAX Options.

**Comment by 2mas** [comment] 2018-07-09 08:40
@argontus Nice that you found out the cause, ofcourse not the ultimate solution to have to disable stuff. I'll see if I can solve this somehow (see below).

@drewnoakes There is an open issue with ReSharper that prevents modifying multiple selections when activating CamelHumps

I think the main thing about interferences (also CopyAsHtml) is that those extensions are first to handle the command, and then terminates the chain instead of calling the next handler, which stops this extension from processing the same command over multiple occurrences. 

If we could somehow handle the commands first and pass the command on to other extensions, I believe alot of possible interference would disappear. So what I'm looking for is to register the commandfilter as early as possible

**Comment by 2mas** [comment] 2021-11-15 07:25
Better to close this since I won't be digging more into this one. Thanks for reporting and contributing!

**Closed by 2mas** 2021-11-15 07:25 UTC
Labels: conflict
